spring:
  thymeleaf:
    prefix: classpath:/static/
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://120.79.96.220:3306/android?characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80